create database customer_behavior;
use customer_behavior;
select * from customer_with_age_group limit 20 ;
-- Q1 what is the total revenue generated by male vs female customers?

select gender, SUM(`Purchase Amount (USD)`) as revenue from customer_with_age_group group by gender;
describe customer_with_age_group ;

-- 	Q2 which customers used a discount but still spent more than the average purchase mount ?

 SELECT `Customer ID`, `Purchase Amount (USD)`
FROM customer_with_age_group 
WHERE `Discount Applied` = 'Yes' 
  AND `Purchase Amount (USD)` >= (SELECT AVG(`Purchase Amount (USD)`) FROM customer_with_age_group );
  
  -- Q3. which are the top 5 products with the highest average review rating?
 
 select `Item Purchased`, round(avg(`Review Rating`),2) as "avg_rating" from customer_with_age_group  group by `Item Purchased` order by avg_rating desc limit 5;
 
  -- Q4 compare the average purchase amounts between standard and express shipping ?
  
  select `Shipping Type`, round(avg (`Purchase Amount (USD)`),2) from customer_with_age_group  where `Shipping Type` in ('Standard','Express') group by `Shipping Type`;
  
   -- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
    select `Subscription Status` ,count(`Customer ID`) as `total_customers`, round(avg(`Purchase Amount (USD)`),2) as avg_spend,round(sum(`Purchase Amount (USD)`),2) as `total_revenue` from customer_with_age_group  group by `Subscription Status` order by total_revenue,avg_spend desc;

    -- Q6 which 5 products have the highest percentage of purchase  with discount applied?

select `Item Purchased`,round(100 * sum(case when `Discount Applied` = 'yes' then 1 else 0 end)/count(*),2) as `discount_rate` from customer_with_age_group  group by `Item Purchased` order by `discount_rate` desc limit 5;

    -- Q7  Segment customers into new,returning, and loyal based on their total numnber of previous purchases, and show the count of each segment?

 with customer_type as( select `Customer ID`,`Previous Purchases`, case when `Previous Purchases` = 1 then 'New' when `Previous Purchases` between 2 and 10 then 'Returning' else 'Loyal' end as customer_segment  from customer_with_age_group ) select customer_segment ,count(*) as "Number of customers" from customer_type group by customer_segment;
 
 -- -- Q8 what are the top 3 most purchased products within each category?
  
   with item_counts as ( select `Category`,`Item Purchased`, count(`Customer ID`) as total_orders, row_number() over (partition by `Category` order by count(`Customer ID`) desc) as item_rank from customer_with_age_group  group by `Category`, `item purchased` ) select item_rank,`Category`,`Item Purchased`,total_orders from item_counts where item_rank <=3;

   -- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
    
   select `Subscription Status` , count(`Customer ID`) as repeat_buyers from customer_with_age_group  where `Previous Purchases`>5 group by `Subscription Status`
   
   -- Q10 what is the revenue contribution of each age group?
    
   SELECT
  CASE
    WHEN Age < 25 THEN 'Below 25'
    WHEN Age BETWEEN 25 AND 34 THEN '25–34'
    WHEN Age BETWEEN 35 AND 44 THEN '35–44'
    WHEN Age BETWEEN 45 AND 54 THEN '45–54'
    ELSE '55+'
  END AS age_group,
  SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

truncate table customer;
select * from customer_with_age_group;
 -- Q10 what is the revenue contribution of each age group?
 select `Age_group` , sum(`Purchase Amount (USD)`) as total_revenue from customer_with_age_group group by `Age_group` order by total_revenue desc;
 select * from customer_with_age_group 